#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/apps/server/src/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Installing $app... please be patient !"

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app npm ci --quiet
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# INITIALIZE DATABASE
#=================================================
ynh_script_progression "Initializing database..."

pushd "$install_dir/apps"
	ynh_hide_warnings ynh_exec_as_app DATA_PATH=$data_dir npm build:migrations
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# LOGROTATE
#=================================================
ynh_script_progression "Configuring logrotate to manage application logfiles"

mkdir -p "/var/log/$app"
touch "/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="$app's service" --log=/var/log/$app/$app.log

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"  --wait_until=""

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"