#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/apps/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Upgrading $app... please be patient !"

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app npm ci --quiet
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# MIGRATE DATABASE
#=================================================
ynh_script_progression "Migrating database..."

pushd "$install_dir/apps"
	ynh_hide_warnings ynh_exec_as_app npm run -w server knex migrate:latest
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="$app's service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"